<?php
require_once '../controller/Controller.php';
$control = new Controller();
?>
<!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un Sujet</h2>

<!-- Formulaire de mise à jour d'un article -->
<article id="article" class="add_posts formAdmin">
<form class="ui form" name="myForm" action="../controller/editSubjectController.php?id=<?= $donnees['id']; ?>" method="post">
    <!-- Utilisation d'un champ caché pour spécifier à quel article rattacher le Sujet -->
    <input type="hidden" name="subjectId" value="<?= intval($donnees['id']) ?>">

    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i>Mettre à jour votre Sujet</legend>
        <article class="ui form">
            <label for="titleSubj">Titre</label>
            <input type="text" id="titleSubj" name="titleSubj" value="<?= $_POST['titleSubj'] ?? $donnees['title'] ?>">
        </article>
        <article class="ui form">
            <label for="contentSubj">Contenu</label>
            <textarea id="contentSubj" name="contentSubj" rows="5"><?= $donnees['content'] ?></textarea>
        </article>
        <p>
        <label for="category">Catégorie de l'article</label><br />
            <select name="category" id="categori">
            <?php foreach ($donnees3 as $value) : ?>    
            <option value="<?= $value['id'] ?>" <?= $value['name'] == $donnees['name'] ? 'selected' : ''  ?>><?= $value['name'] ?></option>
            <?php endforeach; ?>
        </select>
        </p>
        <button class="ui button" onclick="return isEmpty()" type="submit" value>Enregistrer</button>
        <a id="annuler" class="negative ui button" href="../index.php">Annuler</a>
    </fieldset>
</form>
</article>