<?php
if (session_status() == PHP_SESSION_NONE) {
	session_start();
}
?><!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="../public/css/all.min.css">
    <link rel="stylesheet" href="../public/css/bootstrap.min.css">
	<link rel="stylesheet" href="../public/css/normalize.css">
	<link rel="stylesheet" href="../public/css/style.css" />
	<title>Exo Blog</title>
</head>

<body>
    <header>

		<!---------MENU DEKSTOP-------->
		<section>
			<nav id="menu" class="dekstop">
				<ul>
					<li><a href="../index.php">Accueil</a></li>
					<?php if (!empty($_SESSION) and array_key_exists('user', $_SESSION) and $_SESSION['user']['admin']) : ?> 
                        <?php if (!empty($_SESSION) and array_key_exists('user', $_SESSION) and $_SESSION['user']['admin']) : ?><a href="../controller/adminController.php" class="ui primary button">ADMIN</a>
                        <?php endif; ?>
                    <?php endif; ?>
				</ul>
			</nav>
		</section>

		<!------ MENU MOBILE-------->
		    
		<nav class="main-navigation">
            <div class="nav-wrapper">
				<input type="checkbox" id="menu-checkbox" class="menu-checkbox">
				<label for="menu-checkbox" class="menu-toggle">≡ Menu</label>
                <ul class="menu">
                    <li><a href="../index.php">Accueil</a></li>
					<?php if (!empty($_SESSION) and array_key_exists('user', $_SESSION) and $_SESSION['user']['admin']) : ?> 
                        <?php if (!empty($_SESSION) and array_key_exists('user', $_SESSION) and $_SESSION['user']['admin']) : ?><a href="../controller/adminController.php" class="ui primary button">ADMIN</a>
                        <?php endif; ?>
                    <?php endif; ?>
                </ul>
            </div> 
        </nav>
	</header>
	
    <main class="clear">
		<?php include $template . '.phtml' ?>
		<a id="cRetour" class="cInvisible" href="#haut"></a>
	</main>

    <footer>
		<p class="adress">Blog créé par <a href="https://www.linkedin.com/in/matthieu-jacquemin-a15485183/" target="_blank">JACQUEMIN Matthieu</a></p>
	</footer>
	<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="../public/js/main.js"></script>   
</body>
</html>